### PR TITLE
fix: fixed release build info

### LINKED ISSUE #438: IsReleaseBuild() returns incorrect info.
### TL;DR

Ideally,  `IsReleaseBuild` returns true if this binary was built by goreleaser as part of
// the official release process (as opposed to a user just running "go build",
// or running in a CI environment, or something else). But somehow when I install abc cli via `go install ./...`, or https://github.com/abcxyz/abc/blob/23068d1417191358257a9663cc3bf10dffcffe1b/cmd/abc/abc_test.go#L66, `IsReleaseBuild` also returns true

### Expected behavior

_No response_

### Observed behavior

_No response_

### Environment Details

```markdown
N/A
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by capri-xiyue**
fixed #438

### CODE REVIEW

File: internal/version/version.go [hunk 1]
```diff
@@ -44,11 +48,8 @@ var (
 // the official release process (as opposed to a user just running "go build",
 // or running in a CI environment, or something else).
 func IsReleaseBuild() bool {
-	// "source" is a sentinel value returned from buildinfo.Version() when the
-	// build metadata is not present. The build metadata is filled in with the
-	// "-X" flag during release builds, so if it's not present, this binary is
-	// not a release build.
-	return Version != "source"
+	// Binary from release build should follow semver format.
```
Comment (capri-xiyue) [inline internal/version/version.go:51]: Previously logic doesn't work because for `go install ./...` and code in `main` package, the Version will be `(devel)` instead of "source"

File: internal/version/version.go [hunk 2]
```diff
@@ -44,11 +48,8 @@ var (
...
+	return semver.IsValid(Version)
```
Comment (capri-xiyue) [inline internal/version/version.go:52]: I checked the code, the Version here should starts with "v". When we released v0.0.6-rc, we'd better double check it.

File: internal/version/version.go [hunk 3]
```diff
@@ -44,11 +48,8 @@ var (
 // the official release process (as opposed to a user just running "go build",
 // or running in a CI environment, or something else).
 func IsReleaseBuild() bool {
-	// "source" is a sentinel value returned from buildinfo.Version() when the
-	// build metadata is not present. The build metadata is filled in with the
-	// "-X" flag during release builds, so if it's not present, this binary is
-	// not a release build.
-	return Version != "source"
+	// Binary from release build should follow semver format.
+	return semver.IsValid("v" + Version)
```
Comment (capri-xiyue) [inline internal/version/version.go:52]: I googled it. Looks like the Version should not have `v` prefix by default. Let me know if I'm wrong

Comment (capri-xiyue) [reply internal/version/version.go:52]: But I saw some conflicts, when I run `abc templates -version` on v0.0.5, it shows `abc v0.5.0 (HEAD, darwin/amd64)` from `HumanVersion = Name + " " + Version + " (" + Commit + ", " + OSArch + ")"`, looks like `Version` has v prefix.

But for https://github.com/abcxyz/abc/blob/3d99e9bae57b99bc551904ab1b916ecd3c9c4118/.goreleaser.yaml#L50, and the 
Screenshot 2024-02-14 at 9 25 54 PM, the `Version` doesn't have v prefix

**Review by drevell — APPROVED** [review]
